paths:
  data_url: "https://archive.ics.uci.edu/ml/machine-learning-databases/00601/ai4i2020.csv"
  save_path: "data/raw/ai4i2020.csv"
  processed_data_dir: "data/processed"
  processor_path: "data/processed/preprocessor.joblib"
  model_dir: models


features:
  target_cols:
    - "TWF"
    - "HDF"
    - "PWF"
    - "OSF"
    - "RNF"
data:
  label_columns:
    - TWF
    - HDF
    - PWF
    - OSF
    - RNF


  num_features:
    - "Air temperature [K]"
    - "Process temperature [K]"
    - "Rotational speed [rpm]"
    - "Torque [Nm]"
    - "Tool wear [min]"

  cat_features:
    - "Type"

mlflow:
  experiment_name: "Maintenance_Prediction_Experiment"

models:
  logreg:
    class_weight: "balanced"
    max_iter: 1000
    n_jobs: -1

  random_forest:
    class_weight: "balanced"
    n_estimators: 300
    max_depth: null
    random_state: 42
    n_jobs: -1

  xgboost:
    objective: "binary:logistic"
    eval_metric: "logloss"
    n_estimators: 300
    learning_rate: 0.1
    max_depth: 6
    subsample: 0.8
    colsample_bytree: 0.8
    n_jobs: -1
